### ISSUE TITLE
Enums are exported as types, cannot be used

### ISSUE THREAD

**Issue by EcksDy** [OpenAPI-Qraft/openapi-qraft#108]
Enums inside `schema.ts` are exported correctly. But then inside of `index.ts` everything is exported as types:
```
export type * from "./schema";
```

This leads to the following error when trying to use the enums:
```
'SomeEnum' cannot be used as a value because it was exported using 'export type'. ts(1362)
```

**Comment by radist2s** [comment]
@EcksDy, thank you for the feedback, I'll fix it.

**Comment by radist2s** [comment]
@EcksDy, I've just released a new `@openapi-qraft/cli@1.12.1-beta.0`, could you please clarify if this works as intended?

**Comment by EcksDy** [comment]
Works as intended 🙏

**Comment by radist2s** [comment]
Fixed in [`@openapi-qraft/tanstack-query-react-plugin@1.12.1`](https://github.com/OpenAPI-Qraft/openapi-qraft/releases/tag/%40openapi-qraft%2Ftanstack-query-react-plugin%401.12.1).
