### ISSUE TITLE
ERR_IMPORT_ASSERTION_TYPE_MISSING

### ISSUE THREAD

**Issue by lkarcol** [OpenAPI-Qraft/openapi-qraft#129]
Hello, nice project

After installing the latest version, I get this error during generation

`TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "***/platform/node_modules/.pnpm/@openapi-qraft+plugin@1.14.0-beta.0_typescript@5.3.3/node_modules/@openapi-qraft/plugin/package.json" needs an import assertion of type "json"`

Same for v 1.13.0

Node version 20.9.0

Downgrade to Node version 18.20.3 works

`npx @openapi-qraft/cli --plugin tanstack-query-react --plugin openapi-typescript http://localhost:3333/apidoc --output-dir src/api`

**Comment by radist2s** [comment]
@lkarcol, thank you for the report. I'll find a workaround to this problem.

**Comment by radist2s** [comment]
@lkarcol, try **v1.13.1**, it should work help.

**Comment by lkarcol** [comment]
@radist2s nice,  now work

**Comment by radist2s** [comment]
Thank you for the report!
