### ISSUE TITLE
Query for Post request

### ISSUE THREAD

**Issue by wengergruppe** [OpenAPI-Qraft/openapi-qraft#188]
Hi, is there way to override config to generate Query for requests with method POST instead of mutation.

**Comment by radist2s** [comment]
@wengergruppe, thank you for your question. Currently, Qraft doesn’t support transforming operations from one method (e.g., mutation) to another, and we don’t have any plans to add such functionality.

If you’re looking to modify your OpenAPI Document by changing the operation type (e.g., from `GET` to `POST`), you might need to use a third-party OpenAPI transformation tool.

I’ll mention @hkosova here, who might be able to suggest some tools or workflows to help with this kind of transformation.

**Comment by radist2s** [comment]
Closed due to lack of response.
