### ISSUE TITLE
typed hook callbacks

### ISSUE THREAD

**Issue by lkarcol** [OpenAPI-Qraft/openapi-qraft#200]
Hello,

version: 2.0.0-next.12

callback parameters are not more typed ? (data,variables)

```
const { mutateAsync: updateAppearance } =
   apiClient.page.updatePage.useMutation({
      onSuccess(data, variables, context) {
    },
});
```
This  works

```
updateAppearance({},{
    onSuccess(data, variables, context) {
    },
  });
```

**Comment by radist2s** [comment]
@lkarcol, thank you for the question. `<service>.<operatiom>.useMutation(...)` hook requires a first argument to be a predefined parameter, or `undefined`.
In your case, you could use:

```tsx
const { mutateAsync: updateAppearance } =
   apiClient.page.updatePage.useMutation(undefined, {
    onSuccess(data, variables, context) {
      // ...
    },
});

updateAppearance({...}, {
  onSuccess(data, variables, context) {
    // ...
  },
});
```

**Comment by lkarcol** [comment]
@radist2s  Thanks for response,

this is how I used it in version 1.x, but for some reason it doesn't work for me now.

is it possible that I did the migration  to v 2.x wrong?

**Comment by radist2s** [comment]
@lkarcol, did you apply _codemode_ to the migration?

**Comment by lkarcol** [comment]
@radist2s  yes, is small code base so i also removed instaled and generate again.

But it looks it missing types also for options. 

`(method) useMutation<MutationVariables<{
    profileImage?: string;
    title?: {
        value: string;
        color: string;
        fontSize: number;
        font: string;
    } | null;
    ... 5 more ...;
    logo?: boolean;
}, UpdateAppearanceParameters>, unknown>(parameters: void, options?: any): UseMutationResult<{
    ...;
}, unknown | Error, MutationVariables<...>, unknown> (+1 overload)`

But generated services looks good to me

`useMutation<TVariables extends MutationVariables<UpdateAppearanceBody, UpdateAppearanceParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<UpdateAppearanceSchema, UpdateAppearanceData, UpdateAppearanceParameters, TVariables, UpdateAppearanceError, TContext>): UseMutationResult<UpdateAppearanceData, UpdateAppearanceError | Error, TVariables, TContext>;`

**Comment by radist2s** [comment]
@lkarcol, I think it's some kind of corner case. Could you provide an OpenAPI Document from which you are generating the client or at least a problematic endpoint?

**Comment by lkarcol** [comment]
@radist2s I reduced the whole scheme to 1 endpoint

[Schema](https://ctxt.io/2/AAC4OYkAFw)

My command

```
 npx @openapi-qraft/cli --plugin tanstack-query-react --plugin openapi-typescript http://localhost:3333/apidoc --output-dir src/api --explicit-component-exports
```

**Comment by radist2s** [comment]
@lkarcol, unfortunately, the link is expired. Could you please provide a newer one?

**Comment by lkarcol** [comment]
@radist2s [schema](https://justpaste.it/cbw6b)

**Comment by radist2s** [comment]
@lkarcol, sorry for the long reply. I checked and it looks like everything is working correctly.

```ts
  const { mutate, error, isSuccess, isPending } =
    // undefined is used if there are no predefined mutation parameters
    qraft.bio.updateAppearance.useMutation(undefined, {
      onSuccess() {
        // ...
      },
    });

  mutate();
  mutate({ body: { profileImage: "https://i.imgur.com/wSTFkRM.png" } });
```

an alternative approach:

```ts
  const { mutate, error, isSuccess, isPending } =
    qraft.bio.updateAppearance.useMutation(
      {},
      {
        onSuccess: async (updatedUser) => {
          // ...
        },
      },
    );

  mutate();
  mutate({ profileImage: "https://i.imgur.com/wSTFkRM.png" });
```

For example, if you would have an `updateAppearanceById` operation:


```ts
  const { mutate, error, isSuccess, isPending } =
    qraft.bio.updateAppearanceById.useMutation(
      {
        path: { id: somePredefinedId },
      },
      {
        onSuccess: async () => {
          // ...
        },
      },
    );

  mutate();
  mutate({ profileImage: "https://i.imgur.com/wSTFkRM.png" });
```

**Comment by lkarcol** [comment]
@radist2s thanks for response, 

For some reason  did not install this package `@openapi-qraft/tanstack-query-react-types` i had to install it manually
now it works

**Comment by lkarcol** [comment]
@radist2s I dont know why this happen sometimes, i had also problem with `@tanstack/query-core` which part of `@tanstack/react-query` .  I am not sure if this happen because i run` pnpm install` from pnpm workspace root or is something else, i need figure out.

But this is solved, it is problem on my side.
Thx for your time. It is really nice project.
